Su\RestaurantBundle\Entity\ClientOrder:
    type: entity
    table: client_order
    indexes:
        order_dish_id:
            columns:
                - order_dish_id
    uniqueConstraints:
        id:
            columns:
                - id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        orderDishId:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: order_dish_id
        deliveryFee:
            type: float
            nullable: false
            precision: 3
            scale: 2
            column: delivery_fee
        tax:
            type: float
            nullable: false
            precision: 3
            scale: 2
        total:
            type: float
            nullable: false
            precision: 4
            scale: 2
        creationDate:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: creation_date
    lifecycleCallbacks: {  }
