Su\RestaurantBundle\Entity\DeliveryOrder:
    type: entity
    table: delivery_order
    indexes:
        client_id:
            columns:
                - client_id
        address_id:
            columns:
                - address_id
        client_order_id:
            columns:
                - client_order_id
    uniqueConstraints:
        id:
            columns:
                - id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        clientOrderId:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: client_order_id
        addressId:
            type: integer
            nullable: true
            options:
                unsigned: false
        clientId:
            type: integer
            nullable: true
            options:
                unsigned: false
        status:
            type: integer
            nullable: false
            options:
                unsigned: false
        updateDate:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: update_date
    lifecycleCallbacks: {  }
