Su\RestaurantBundle\Entity\Dish:
    type: entity
    table: dish
    indexes:
        category:
            columns:
                - category
    uniqueConstraints:
        name:
            columns:
                - name
    id:
        dishId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: dish_id
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        description:
            type: string
            nullable: false
            length: 256
            options:
                fixed: false
        price:
            type: float
            nullable: false
            precision: 3
            scale: 2
        image:
            type: string
            nullable: false
            length: 1000
            options:
                fixed: false
        category:
            type: integer
            nullable: false
            options:
                unsigned: false
        shop:
            type: integer
            nullable: false
            options:
                unsigned: false
        creationDate:
            type: datetime
            nullable: false
            column: creation_date
        updateDate:
            type: datetime
            nullable: true
            column: update_date
    lifecycleCallbacks: {  }
